[package]
edition = "2021"
name = "raytracer_in_one_weekend_benchmark"
version = "0.1.0"

[profile.release]
debug = true

[[bench]]
harness = false
name = "my_benchmark"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"
